### ISSUE TITLE
Python kubernetes dependency is broken when using it with GKE (and potentially other cloud providers) at the moment

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/integration-tests#186]
I tried using the `./access_services.py` with a GKE cluster today and got the following error:

```
(⎈ |gke_engineering-329019_europe-central2-a_elia:default)➜  demo ./access_services.py --namespace s-iot -d                                                                                                                <<<
Traceback (most recent call last):
  File "/home/sliebau/stackable/demo/./access_services.py", line 198, in <module>
    sys.exit(main())
  File "/home/sliebau/stackable/demo/./access_services.py", line 83, in main
    for node in K8S.list_node().items:
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 16844, in list_node
    return self.list_node_with_http_info(**kwargs)  # noqa: E501
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 16951, in list_node_with_http_info
    return self.api_client.call_api(
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 192, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 264, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 303, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 639, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 280, in __deserialize
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 280, in <listcomp>
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 303, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 639, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 303, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 639, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 280, in __deserialize
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 280, in <listcomp>
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 303, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 641, in __deserialize_model
    instance = klass(**kwargs)
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/models/v1_node_condition.py", line 76, in __init__
    self.type = type
  File "/home/sliebau/.local/lib/python3.10/site-packages/kubernetes/client/models/v1_node_condition.py", line 219, in type
    raise ValueError(
ValueError: Invalid value for `type` (FrequentUnregisterNetDevice), must be one of ['DiskPressure', 'MemoryPressure', 'NetworkUnavailable', 'PIDPressure', 'Ready']
(⎈ |gke_engineering-329019_europe-central2-a_elia:default)➜  demo
```

Which @sbernauer  found out originates here: https://github.com/kubernetes-client/python/blob/ab14a3e35b70256e5304896f574f0d5ddfc1024d/kubernetes/client/models/v1_node_condition.py#L219

It looks like this recently broken in the k8s client due to this field accidentally being marked as enum and validated against a too restrictive list of values.

Issue: https://github.com/kubernetes-client/python/issues/1735
PR: https://github.com/kubernetes/kubernetes/pull/108639

**Comment by soenkeliebau** [comment]
https://github.com/kubernetes/kubernetes/pull/108639 got merged not sure if that is all that is needed, the ticket and PR solution is a bit fishy on their end

**Comment by sbernauer** [comment]
`pip install --upgrade pip && pip install kubernetes==` doesn't show any new version yet...

**Comment by soenkeliebau** [comment]
It has been cherry-picked into some release branch: https://github.com/kubernetes/kubernetes/pull/108740

Not sure what that means though :)

**Comment by lfrancke** [comment]
This is fixed by downgrading, correct?
If it is: Can we close this issue knowing that we might want to rewrite this in Rust anyway?

**Comment by sbernauer** [comment]
Correct and fine for me
