### ISSUE TITLE
Nit: Add docker requirement to documentation 

### ISSUE THREAD

**Issue by timrobertson100** [stackabletech/integration-tests#201]
The readme is excellent, but overlooks the need to have docker installed and running.

```
tim@iMac-2 integration-tests % python3 create_test_cluster.py --kind --operator hbase
Traceback (most recent call last):
  File "create_test_cluster.py", line 512, in <module>
    sys.exit(main())
  File "create_test_cluster.py", line 494, in main
    create_kind_cluster(args.kind)
  File "create_test_cluster.py", line 144, in create_kind_cluster
    helper_check_docker_running()
  File "create_test_cluster.py", line 224, in helper_check_docker_running
    output = subprocess.run(['docker', 'info'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
```

Suggest adding that in the *requirements* section for completeness.

**Comment by sbernauer** [comment]
Thanks for your suggestion! Created https://github.com/stackabletech/integration-tests/pull/208 for this

**Comment by sbernauer** [comment]
Merged
